### ISSUE TITLE
Join efforts with jstoone/HTMLFormValidator

### ISSUE THREAD

**Issue by Ocramius** [xtreamwayz/html-form-validator#1]
See jstoone/HTMLFormValidator#1 - some reviews are really relevant for this repo as well /cc @jstoone

Sorry for not notifying that @jstoone was already giving it a shot, I just really want to avoid having you folks work on 20 flavors of the same thing while maybe repeating the same thought process.

If you are interested in working on it, maybe you should team up before you reach a stable API =)

**Comment by xtreamwayz** [comment]
Ok, thanx for letting me know. I'll stop with this and will watch the repo from @jstoone. I'll try to help out there when I can.

**Comment by Ocramius** [comment]
@xtreamwayz no need to stop, just make sure you two have a chat or something =D

**Comment by jstoone** [comment]
Thanks for referencing my repo, @Ocramius.
When I'm done with the new PR, featuring the changes mentioned in my last PR, I'll be sure to drop a note here on the thread, if you are interested @xtreamwayz?

Happy holidays.

**Comment by jstoone** [comment]
Hey @xtreamwayz, just wanted to let you know that I've now pushed the new version/PR.
I would love your feedback. :)

https://github.com/jstoone/HTMLFormValidator/pull/2
