### ISSUE TITLE
Improve compatibility with value objects and entity relations

### ISSUE THREAD

**Issue by xtreamwayz** [xtreamwayz/html-form-validator#53]
#52 introduced the ability to use an object as default data. However this goes wrong in several cases:

**If the returned value is null**
Probably detection for this and converting it to an empty string is enough.

**If the returned value is a DateTime object**
Convert it to a standard 'Y-m-d H:i:s' string?

**If the returned value is an object** _(value object other entity)_
Maybe add something like how Symfony handles forms. Set the name to something like 'methodName[method]'. e.g. `<input type="text" name="address[street]"` />`. 
This would then execute `$defaultData->getAddress()->getStreet();`

**Comment by xtreamwayz** [comment]
Or maybe just revert #52 since it makes it a lot more complicated.

**Comment by Ocramius** [comment]
I would suggest rejecting objects completely: it's out of scope for the library, IMO.

**Comment by xtreamwayz** [comment]
Well it prevents a lot of typing. But I already stumbled upon some issues and I'm pretty sure more issues will be reported once others are going to use this library.

I think I'll take your advice and keep it simple.

**Comment by Ocramius** [comment]
@xtreamwayz that's the bit handled by hydrators & co - I wouldn't rewrite it. Keep it all arrays for now, and you'll be fine.

**Comment by xtreamwayz** [comment]
Thanx
