### ISSUE TITLE
add it to be installed via composer 

### ISSUE THREAD

**Issue by jkhaled** [xtreamwayz/html-form-validator#6]
can you add this nice form validator to be installed from composer;

**Comment by xtreamwayz** [comment]
Did that last night :)

``composer require xtreamwayz/html-form-validator``

However I didn't release anything yet. I'll do a first release now.

**Comment by xtreamwayz** [comment]
First pre-release done as well.

**Comment by jkhaled** [comment]
Could not find package xtreamwayz/html-form-validator at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by xtreamwayz** [comment]
Weird, might be an issue with the composer cache. The release is listed on packagist: https://packagist.org/packages/xtreamwayz/html-form-validator

**Comment by jkhaled** [comment]
yes its done ;) thanks
