### ISSUE TITLE
Input names with array indicator will not handled properly

### ISSUE THREAD

**Issue by oqq** [xtreamwayz/html-form-validator#66]
Hi!

I have some form constructions with fields have array indicators in here names.
Sometimes to deal with capability of multiple selects, but also for dynamic input clones.

After some tests i don't have found a way to handle this conditions with your library.
The one point i have to fault. I prefer yours over all public components (zend form, symfony form, ?? )
#### multiple checkboxes

A collection of checkboxes with undefined amount of required values to choose.
With a refer to http://www.w3.org/TR/html401/interact/forms.html#checkbox, several checkboxes could share there name. Since PHP could handle this behavior only with array´s (with $_POST, which should be used for ServerRequestInterface), there is no better way for me as suffix the name attribute with '[]'.

``` html
<form>
    <input type="checkbox" name="category[]" multiple data-min="2" data-max="3" value="category1" />
    <input type="checkbox" name="category[]" value="category2" />
    <input type="checkbox" name="category[]" value="category3" />
    <input type="checkbox" name="category[]" value="category4" />
</form>
```

Also it would be awesome if i can define a max or min amount the user have to choose.
Filters should be set on the first checkbox from collection and have an "multiple" attribute (or all of them). Maybe a "Attribute-Holder-Tag" such as a datalist would be the better way.
#### multi text inputs

How about text input collection with a variable amount of inputs? Also with filters and an option to restrict the valid amount of elements.

``` html
<form>
    <input type="text" name="tag[]" multiple data-filters="trim" data-max="4" />
    <button data-action="call:add-another-one-javascript-shizzle"></button>
</form>
```

There are many more examples, but i think you get the point.
I know that would be a kind of magic, at least with names like **category[group1][]**. But many clients wanna have such UI-Magic.

Whats your opinion about that? Is it to ✨? I can put some contributions if you like.

Or someone (@ocramius) have some suggestions how to solve it in a much cleaner way?

Thanks!

**Comment by xtreamwayz** [comment]
I was pretty sure I read somewhere that `name="tag[]"` was considered illegal for html5. But I can't find it anymore. But what I did find is what you explained above: multiple elements with the same name are allowed and return an array. If using `name="tag[]"` is the only way to accomplish this then so be it and add this php hack.

So far I've got around it with using this: 
```html
<form>
    <input type="checkbox" name="category_1" value="category_1" />
    <input type="checkbox" name="category_2" value="category_2" />
    ....
</form>
```

To get all the dynamic tags I add a hidden element and add all tags as a comma separated list.

```html
<input type="hidden" name="tags" value="tag1, tag 2, t a g 3, tag4" />
```

So back on why this would be needed... 
- If you add form elements with JavaScript they will not be validated. 
- It's in the html specs so it should be supported.
- It's nicer and easier to have an array returned than manually grabbing all tag_x elements and convert it to an array.

Possible implementation examples:

```html
<div data-group="tags" data-group-min="1" data-group-max="4" data-reuse-submitted-value="true" data-filters="striptags|stringtrim" data-validators="">
    <input type="text" name="tags" value="tag1" />
    <input type="text" name="tags" value="tag2" />
    <input type="text" name="tags" value="tag3" />
</div>

<div data-group="tags" data-group-min="1">
    <label><input type=checkbox name="topping" value="Mushroom">Mushroom</label>
    <label><input type=checkbox name="topping" value="Extra Cheese">Extra Cheese</label>
    <label><input type=checkbox name="topping" value="Onion">Onion</label>
    <label><input type=checkbox name="topping" value="Mushroom">Mushroom</label>
</div>
```

- data-group-min="1": Minimal required values set.
- data-group-max="4": Maximum allowed set values.
- data-reuse-submitted-value, data-filters and data-validators: These should be applied to all input elements in the same group.
- Submitted values not set in the from should be added.
- If an element in a data-group doesn't have the brackets suffix it should be added to make it work with PHP.

Anything else I'm missing?

**Comment by oqq** [comment]
> Submitted values not set in the from should be added.

- This should also be configurable, either it is allowed to add additional values or not.

> If an element in a data-group doesn't have the brackets suffix it should be added to make it work with PHP.

- Could also solved with "_n" suffixes if html5 denies brackets in names

- Data groups and each input should have a distinct "error-message-div", to separate messages like "to many values" and "input does not match pattern".
- Don't miss data-groups from select´s with attribute "multiple" set. This could conflict with added bracket suffixes
- Also removing a predefined value should be valid, maybe configureable on group level and on element level.

**Comment by xtreamwayz** [comment]
> Also removing a predefined value should be valid, maybe configureable on group level and on element level.

This should already be possible. If an element doesn't have the required attribute set, you can remove it.

This reminds me I should write some tests to simulate changing the form with JavaScript.
